name: Deploy to IBM Code Engine

on:
  push:
    branches:
      - main_aes

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install IBM Cloud CLI  # Install CLI before login
      run: curl -fsSL https://clis.cloud.ibm.com/install/linux | sh

    - name: Log in to IBM Cloud Container Registry
      run: echo ${{ secrets.IBM_CLOUD_API_KEY }} | ibmcloud login --apikey-stdin -a https://cloud.ibm.com -r eu-gb 

    - name: Build and push Docker image
      run: |
        docker build -t uk.icr.io/coffee-roulette-bot/aes-coffee-roulette-bot:latest .
        docker push uk.icr.io/coffee-roulette-bot/aes-coffee-roulette-bot:latest

    - name: Log in to IBM Cloud  # Login after CLI installation
      run: ibmcloud login --apikey ${{ secrets.IBM_CLOUD_API_KEY }} -r eu-gb 

    - name: Update IBM Code Engine app
      run: |
        ibmcloud target -g coffee-roulette-bot
        ibmcloud ce application update --name aes-coffee-roulette-bot --image uk.icr.io/coffee-roulette-bot/aes-coffee-roulette-bot:latest
