name: Deploy to IBM Code Engine

on:
  push:
    branches:
      - main_cds

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install IBM Cloud CLI
      run: curl -fsSL https://clis.cloud.ibm.com/install/linux | sh

    - name: Install IBM Cloud Container Registry plugin
      run: ibmcloud plugin install container-registry

    - name: Install IBM Cloud Code Engine plugin
      run: ibmcloud plugin install code-engine

    - name: Log in to IBM Cloud
      run: ibmcloud login --apikey ${{ secrets.CDS_IBM_CLOUD_API_KEY }} -r eu-gb

    - name: Log in to IBM Cloud Container Registry
      run: ibmcloud cr login

    - name: Build and push Docker image
      run: |
        docker build -t uk.icr.io/coffee-roulette-bot/cds-coffee-roulette-bot:latest .
        docker push uk.icr.io/coffee-roulette-bot/cds-coffee-roulette-bot:latest

    - name: Target resource group
      run: ibmcloud target -g coffee-roulette-bot

    - name: Select Code Engine project
      run: ibmcloud ce project select -n cds-coffee-roulette-bot

    - name: Update IBM Code Engine app
      run: ibmcloud ce application update --name cds-coffee-roulette-bot --image uk.icr.io/coffee-roulette-bot/cds-coffee-roulette-bot:latest
